baseURL = "https://clawler.github.io/ted-personal-site"
publishDir = "docs"
languageCode = "en-us"
title = "TED WINT"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Ted Wint"
    description = "PERSONAL WEBSITE"
    githubUsername = "#"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Oswald" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "HOME"
    weight = 1

[[menu.main]]
    url = "/presume.pdf"
    name = "RESUME"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "POSTS"
    weight = 3

[[menu.main]]
    url = "/portfolio/"
    name = "PORTFOLIO"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:hwint@usc.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/TedAWint/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/tedawint/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "http://instagram.com/tedawint/"
    name = "instagram"
    weight = 4
